# Built-in
custom_path: "/2007/6/3/external-resources-for-application"

# Custom
title: "Внешние ресурсы для приложений"

publicated_at: "06.03.2007"

tags:
- Ruby on Rails
- Subversion
- Version Control
